styles:
    inputs:
        - 'bundles/orocustomer/blank/scss/variables/single-form-page-config.scss'
        - 'bundles/orocustomer/blank/scss/variables/check-email-config.scss'
        - 'bundles/orocustomer/blank/scss/variables/registration-instructions-config.scss'
        - 'bundles/orocustomer/blank/scss/variables/topbar-customer-menu-config.scss'
        - 'bundles/orocustomer/blank/scss/variables/customer-info-grid-config.scss'
        - 'bundles/orocustomer/blank/scss/variables/customer-line-items-config.scss'
        - 'bundles/orocustomer/blank/scss/variables/info-list-config.scss'
        - 'bundles/orocustomer/blank/scss/variables/customer-profile-config.scss'
        - 'bundles/orocustomer/blank/scss/variables/address-list-config.scss'
        - 'bundles/orocustomer/blank/scss/variables/info-list-status-config.scss'

        - 'bundles/orocustomer/blank/scss/components/topbar-customer-menu.scss'
        - 'bundles/orocustomer/blank/scss/components/address-list.scss'
        - 'bundles/orocustomer/blank/scss/components/customer-profile.scss'
        - 'bundles/orocustomer/blank/scss/components/info-list.scss'
        - 'bundles/orocustomer/blank/scss/components/info-list-status.scss'

        - 'bundles/orocustomer/blank/scss/styles.scss'

print_styles:
    inputs:
        - 'bundles/orocustomer/blank/scss/variables/customer-info-grid-print-config.scss'
        - 'bundles/orocustomer/blank/scss/variables/customer-line-items-print-config.scss'

        - 'bundles/orocustomer/blank/scss/styles-print.scss'
