config:
    paths:
        'orocustomer/js/app/components/password-generate': 'bundles/orocustomer/js/app/components/password-generate.js'
        'orocustomer/js/app/components/customer-user-role-component': 'bundles/orocustomer/js/app/components/customer-user-role-component.js'
        'oro/select2-autocomplete-customeruser-component': 'bundles/orocustomer/js/app/components/select2-autocomplete-customeruser-component.js'
        'orocustomer/js/address-book': 'bundles/orocustomer/js/address-book.js'
        'orocustomer/js/app/components/frontend-customer-address-book-component': 'bundles/orocustomer/js/app/components/frontend-customer-address-book-component.js'
        'oro/datagrid/action/frontend-map-action': 'bundles/orocustomer/js/datagrid/action/frontend-map-action.js'
    appmodules:
        - orocustomer/js/app/modules/views-module
