stylebook_styles:
    inputs:
        - '~prismjs/themes/prism-coy.css'
        - 'bundles/orostylebook/blank/scss/variables/style-book/style-book-colors-config.scss'
        - 'bundles/orostylebook/blank/scss/variables/style-book/style-book-config.scss'
        - 'bundles/orostylebook/blank/scss/variables/style-book/style-book-menu-container-config.scss'
        - 'bundles/orostylebook/blank/scss/variables/style-book/style-book-menu-title-config.scss'
        - 'bundles/orostylebook/blank/scss/variables/style-book/style-book-menu-config.scss'
        - 'bundles/orostylebook/blank/scss/variables/style-book/style-book-header-config.scss'
        - 'bundles/orostylebook/blank/scss/variables/style-book/style-book-sticky-header-config.scss'
        - 'bundles/orostylebook/blank/scss/variables/style-book/style-book-sticky-elements-nav-config.scss'
        - 'bundles/orostylebook/blank/scss/variables/style-book/style-book-page-description-config.scss'
        - 'bundles/orostylebook/blank/scss/variables/style-book/style-book-page-title-config.scss'
        - 'bundles/orostylebook/blank/scss/variables/style-book/style-book-sidebar-config.scss'
        - 'bundles/orostylebook/blank/scss/variables/style-book/style-book-title-config.scss'
        - 'bundles/orostylebook/blank/scss/variables/style-book/style-book-tabs-config.scss'
        - 'bundles/orostylebook/blank/scss/style-book.scss'
    output: 'css/stylebook.css'
