styles:
    inputs:
        - 'bundles/orocustomer/default/scss/settings/global-settings.scss'
        - 'bundles/orocustomer/default/scss/variables/address-form-config.scss'
        - 'bundles/orocustomer/default/scss/variables/primary-menu-container-config.scss'
        - 'bundles/orocustomer/default/scss/variables/primary-menu-title-config.scss'
        - 'bundles/orocustomer/default/scss/variables/map-popover-config.scss'
        - 'bundles/orocustomer/default/scss/variables/registration-instructions-config.scss'
        - 'bundles/orocustomer/default/scss/variables/topbar-customer-menu-config.scss'
        - 'bundles/orocustomer/default/scss/variables/permissions-grid-config.scss'
        - 'bundles/orocustomer/default/scss/variables/action-permissions-config.scss'
        - 'bundles/orocustomer/default/scss/variables/address-list-config.scss'
        - 'bundles/orocustomer/default/scss/variables/capabilities-config.scss'
        - 'bundles/orocustomer/default/scss/variables/customer-form-config.scss'

        - 'bundles/orocustomer/default/scss/components/customer-form.scss'
        - 'bundles/orocustomer/default/scss/components/address-form.scss'
        - 'bundles/orocustomer/default/scss/components/address-form-outer.scss'
        - 'bundles/orocustomer/default/scss/components/capabilities.scss'
        - 'bundles/orocustomer/default/scss/components/address-list.scss'
        - 'bundles/orocustomer/default/scss/components/topbar-customer-menu.scss'

        - 'bundles/orocustomer/default/scss/styles.scss'
