styles:
    inputs:
        - 'bundles/orofrontend/default/vendors/slick/slick.css'
        - 'bundles/orofrontend/default/scss/settings/global-settings.scss'
        - 'bundles/orofrontend/default/scss/variables/base-config.scss'
        - 'bundles/orofrontend/default/scss/variables/custom-icons-config.scss'
        - 'bundles/orofrontend/default/scss/variables/breadcrumbs-config.scss'
        - 'bundles/orofrontend/default/scss/variables/collapse-view-config.scss'
        - 'bundles/orofrontend/default/scss/variables/link-config.scss'
        - 'bundles/orofrontend/default/scss/variables/page-title-config.scss'
        - 'bundles/orofrontend/default/scss/variables/page-subtitle-config.scss'
        - 'bundles/orofrontend/default/scss/variables/page-main-config.scss'
        - 'bundles/orofrontend/default/scss/variables/page-container-config.scss'
        - 'bundles/orofrontend/default/scss/variables/page-content-config.scss'
        - 'bundles/orofrontend/default/scss/variables/page-header-config.scss'
        - 'bundles/orofrontend/default/scss/variables/page-footer-config.scss'
        - 'bundles/orofrontend/default/scss/variables/page-sidebar-config.scss'
        - 'bundles/orofrontend/default/scss/variables/copyright-config.scss'
        - 'bundles/orofrontend/default/scss/variables/section-title-config.scss'
        - 'bundles/orofrontend/default/scss/variables/notifications-config.scss'
        - 'bundles/orofrontend/default/scss/variables/primary-menu-config.scss'
        - 'bundles/orofrontend/default/scss/variables/notification-config.scss'
        - 'bundles/orofrontend/default/scss/variables/notification-flash-config.scss'
        - 'bundles/orofrontend/default/scss/variables/loader-mask-config.scss'
        - 'bundles/orofrontend/default/scss/variables/embedded-list/embedded-list-config.scss'
        - 'bundles/orofrontend/default/scss/variables/datagrid-manager-config.scss'
        - 'bundles/orofrontend/default/scss/variables/ui/dialog-config.scss'
        - 'bundles/orofrontend/default/scss/variables/badge-config.scss'

        - 'bundles/orofrontend/default/scss/components/custom-icons.scss'
        - 'bundles/orofrontend/default/scss/styles.scss'
    output: 'css/layout/default/styles.css'

stylebook_styles:
    inputs:
        - 'bundles/orofrontend/default/scss/settings/global-settings.scss'
        - 'bundles/orofrontend/default/scss/variables/page-main-config.scss'
        - 'bundles/orofrontend/default/scss/variables/style-book/style-book-sticky-elements-nav-config.scss'
        - 'bundles/orofrontend/default/scss/style-book.scss'
    output: 'css/layout/default/stylebook.css'
