dynamic-imports:
    orofrontend:
        - orofrontend/default/js/app/views/fake-masked-input-view
map:
    "*":
        orodatagrid/templates/datagrid/visible-items-counter.html: orofrontend/default/templates/datagrid/visible-items-counter.html
