styles:
    inputs:
        - 'bundles/orocommercemenu/default/scss/variables/main-menu-config.scss'
        - 'bundles/orocommercemenu/default/scss/variables/top-bar-config.scss'
        - 'bundles/orocommercemenu/default/scss/variables/information-nav-config.scss'
        - 'bundles/orocommercemenu/default/scss/variables/quick-access-config.scss'
        - 'bundles/orocommercemenu/default/scss/variables/header-row-config.scss'
        - 'bundles/orocommercemenu/default/scss/variables/nav-trigger-config.scss'

        - 'bundles/orocommercemenu/default/scss/components/header-row.scss'
        - 'bundles/orocommercemenu/default/scss/components/quick-access.scss'
        - 'bundles/orocommercemenu/default/scss/components/top-bar.scss'
        - 'bundles/orocommercemenu/default/scss/components/main-menu/main-menu.scss'
        - 'bundles/orocommercemenu/default/scss/components/main-menu/main-menu-outer.scss'

        - 'bundles/orocommercemenu/default/scss/styles.scss'
