api:
    entity_aliases:
        Oro\Bundle\CommerceMenuBundle\Api\Model\CommerceMenuItem:
            alias: menu
            plural_alias: menus

    entities:
        Oro\Bundle\CommerceMenuBundle\Api\Model\CommerceMenuItem:
            documentation_resource: '@OroCommerceMenuBundle/Resources/doc/api_frontend/commerce_menu_item.md'
            identifier_field_names: [name]
            disable_meta_properties: true
            fields:
                name:
                    data_type: string
                label:
                    data_type: string
                uri:
                    data_type: string
                description:
                    data_type: string
                extras:
                    data_type: object
                link_attributes:
                    data_type: object
                contentNode:
                    target_class: Oro\Bundle\WebCatalogBundle\Entity\ContentNode
                parent:
                    target_class: Oro\Bundle\CommerceMenuBundle\Api\Model\CommerceMenuItem
                    property_path: parentName
                resource:
                    data_type: object
                    property_path: _
                    depends_on: [uri]
            actions:
                get_list:
                    description: Get menu items as a flat list
                    disable_paging: true
                    disable_sorting: true
                get: false
                create: false
                update: false
                delete: false
                delete_list: false
                get_subresource: false
                get_relationship: false
                delete_relationship: false
                add_relationship: false
                update_relationship: false
            filters:
                fields:
                    menu:
                        data_type: string
                        operators: ['=']
                        description: Filter menu items by menu name.
                        options:
                            default_value: frontend_menu
                    depth:
                        data_type: integer
                        operators: ['=']
                        description: Limit the depth of menu tree.

