styles:
    inputs:
        - 'bundles/orofrontend/default/vendors/slick/slick.css'

        # - 'bundles/orofrontend/blank/scss/variables/bootstrap4-variables-config.scss' # Must be first from *.scss
        # - 'bundles/orofrontend/blank/scss/variables/btn-group-config.scss'
        # - 'bundles/orofrontend/blank/scss/variables/bootstrap4-config.scss'

        # Bootstrap Required
        - 'bundles/orofrontend/blank/scss/settings/bootstrap/functions.scss'
        - 'bundles/orofrontend/blank/scss/settings/bootstrap/mixins.scss'
        - 'bundles/orofrontend/blank/scss/settings/bootstrap/overrides.scss'
        - 'bundles/orofrontend/blank/scss/settings/bootstrap/variables.scss'
        - 'bundles/orofrontend/blank/scss/settings/bootstrap/clearing.scss'

        - 'bundles/orofrontend/blank/scss/settings/global-settings.scss'

        - 'bundles/orofrontend/blank/scss/variables/breadcrumbs-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/layout/page-area-container-config.scss'

        - 'bundles/orofrontend/blank/scss/variables/datagrid/datagrid-massaction-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/datagrid/launcher-item-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/datagrid/grid-views-config.scss'

        - 'bundles/orofrontend/blank/scss/variables/filters/filters-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/filters/filters-dropdown-mode-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/filters/filters-toggle-mode-config.scss'

        - 'bundles/orofrontend/blank/scss/variables/select2/select2-container-config.scss'

        - 'bundles/orofrontend/blank/scss/variables/notification-flash-container-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/table-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/fullscreen-popup-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/sorting-popup-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/ui/dialog-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/ui/datepicker-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/ui/extend/ui-multiselect-menu-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/popup-gallery-widget-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/scroll-top-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/pagination-widget-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/embedded-list/embedded-list-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/datagrid-manager-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/warning-list-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/tiny-container-config.scss'

        # Bootstrap Optional Components
        - 'bundles/orofrontend/blank/scss/components/bootstrap/bootstrap.scss'

        - 'bundles/orofrontend/blank/scss/components/ui/jquery-ui.scss'
        - 'bundles/orofrontend/blank/scss/components/ui/datepicker.scss'
        - 'bundles/orofrontend/blank/scss/components/embedded-list/embedded-list.scss'
        - 'bundles/orofrontend/blank/scss/components/datagrid/datagrid-toolbar.scss'
        - 'bundles/orofrontend/blank/scss/components/datagrid-manager.scss'
        - 'bundles/orofrontend/blank/scss/components/datagrid-manager-search.scss'
        - 'bundles/orofrontend/blank/scss/components/datagrid-manager-table.scss'

        - 'bundles/orofrontend/blank/scss/styles.scss'
        - 'bundles/orofrontend/blank/scss/components/select2/select2-container.scss'
        - 'bundles/orofrontend/blank/scss/components/select2/select2-container-multi.scss'
