styles:
    inputs:
        - '~slick-carousel/slick/slick.scss'

        - 'bundles/orofrontend/blank/scss/settings/global-settings.scss'

        # Bootstrap Required
        - 'bundles/orofrontend/blank/scss/settings/bootstrap/functions.scss'
        - 'bundles/orofrontend/blank/scss/settings/bootstrap/mixins.scss'
        - 'bundles/orofrontend/blank/scss/settings/bootstrap/variables.scss'

        # Bootstrap Configs
        - 'bundles/orofrontend/blank/scss/variables/bootstrap/buttons-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/bootstrap/tooltip.scss'
        - 'bundles/orofrontend/blank/scss/variables/bootstrap/table-config.scss'

        - 'bundles/orofrontend/blank/scss/variables/breadcrumbs-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/layout/page-area-container-config.scss'

        - 'bundles/orofrontend/blank/scss/variables/close-dialog-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/datagrid/datagrid-massaction-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/datagrid/launcher-item-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/datagrid/grid-views-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/datagrid/datagrid-filters-config.scss'

        - 'bundles/orofrontend/blank/scss/variables/filters/filters-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/filters/filters-dropdown-mode-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/filters/filters-toggle-mode-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/filters/filters-fullscreen-popup-mode-config.scss'

        - 'bundles/orofrontend/blank/scss/variables/select2/select2-container-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/select2/select2-container-multi-config.scss'

        - 'bundles/orofrontend/blank/scss/variables/notification-flash-container-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/notification-flash-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/table-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/fullscreen-popup-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/sorting-popup-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/ui/jquery-ui-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/ui/dialog-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/ui/datepicker-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/ui/extend/ui-multiselect-menu-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/popup-gallery-widget-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/scroll-top-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/pagination-widget-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/embedded-list/embedded-list-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/datagrid-manager-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/datagrid-manager-search-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/datagrid-manager-table-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/datagrid-divider-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/warning-list-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/headings-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/skip-to-content.scss'
        - 'bundles/orofrontend/blank/scss/variables/notes-config.scss'
        - 'bundles/orofrontend/blank/scss/variables/sticky-panel-config.scss'

        # Bootstrap Optional Components
        - 'bundles/orofrontend/blank/scss/components/bootstrap/bootstrap.scss'

        - 'bundles/orofrontend/blank/scss/components/ui/jquery-ui.scss'
        - 'bundles/orofrontend/blank/scss/components/ui/datepicker.scss'
        - 'bundles/orofrontend/blank/scss/components/skip-to-content.scss'
        - 'bundles/orofrontend/blank/scss/components/embedded-list/embedded-list.scss'
        - 'bundles/orofrontend/blank/scss/components/datagrid/datagrid-toolbar.scss'
        - 'bundles/orofrontend/blank/scss/components/datagrid/datagrid-filters.scss'
        - 'bundles/orofrontend/blank/scss/components/datagrid-manager.scss'
        - 'bundles/orofrontend/blank/scss/components/datagrid-manager-search.scss'
        - 'bundles/orofrontend/blank/scss/components/datagrid-manager-table.scss'

        - 'bundles/orofrontend/blank/scss/styles.scss'
        - 'bundles/orofrontend/blank/scss/components/select2/select2-container.scss'
        - 'bundles/orofrontend/blank/scss/components/select2/select2-container-multi.scss'
        - 'bundles/orofrontend/blank/scss/components/close-dialog.scss'
        - 'bundles/orofrontend/blank/scss/components/sidebar-filter-container.scss'


print_styles:
    inputs:
        - 'bundles/orofrontend/blank/scss/components/datagrid/datagrid-toolbar-print.scss'

        - 'bundles/orofrontend/blank/scss/styles-print.scss'
