placeholders:
    placeholders:
        header_logo:
            items:
                logo:
                    order: 100
                frontend_logo:
                    order: 100

        scripts_after:
            items:
                window_bundle_js:
                    order: 200

        install_additional_configuration_fields:
            items:
                web_settings:
                    order: 300

    items:
        logo:
            template: '@@OroFrontend/Organization/logo.html.twig'
            applicable: "@oro_frontend.placeholder.filter->isBackendRoute()"
        frontend_logo:
            template: '@@OroFrontend/Organization/logo_frontend.html.twig'
            applicable: "@oro_frontend.placeholder.filter->isFrontendRoute()"
        window_bundle_js:
            template: '@@OroWindows/Include/javascript.html.twig'
            applicable: "@oro_frontend.placeholder.filter->isBackendRoute()"
        view_oro_activity_list:
            applicable: '@oro_frontend.activity_list.placeholder.filter->isApplicable($entity$, Oro\Bundle\ActivityBundle\EntityConfig\ActivityScope::VIEW_PAGE)'
            template: '@@OroActivityList/ActivityList/activities.html.twig'
        update_oro_activity_list:
            applicable: '@oro_frontend.activity_list.placeholder.filter->isApplicable($entity$, Oro\Bundle\ActivityBundle\EntityConfig\ActivityScope::UPDATE_PAGE)'
            template: '@@OroActivityList/ActivityList/activities.html.twig'
        web_settings:
            template: '@@OroFrontend/InstallConfiguration/web.html.twig'
        filter_embedded_templates:
            applicable: "@oro_layout.helper->isTemplateRequest()"
        widget_filter_templates:
            applicable: "@oro_layout.helper->isTemplateRequest()"
        orodashboard_widget_items_templates:
            applicable: "@oro_layout.helper->isTemplateRequest()"
        email_filter_templates:
            applicable: "@oro_layout.helper->isTemplateRequest()"
        ui_js_modules_config_public_path:
            applicable: '@oro_frontend.placeholder.filter->isBackendRoute()'
        oro_reminder_subscribe_script:
            applicable:
                - "@oro_frontend.placeholder.filter->isBackendRoute()"
        sync_js:
            applicable:
                - "@oro_security.token_accessor->hasUser()"
                - "@oro_layout.helper->isTemplateRequest()"
